using System.Collections.Generic;

namespace NovelManagement.WPF.Localization
{
    /// <summary>
    /// 词条表：核心（应用标题/主窗口框架/导航/仪表盘/项目管理/项目概览）。
    /// 键前缀约定：App.* 应用级；Nav.* 导航项；Dash.* 仪表盘；PM.* 项目管理；PO.* 项目概览；Common.* 通用。
    /// </summary>
    internal static class StringsCore
    {
        internal static readonly IReadOnlyDictionary<string, LocEntry> Entries = new Dictionary<string, LocEntry>
        {
            // ---- 应用级 ----
            ["App.Name"] = new("书籍管理系统", "NovelCraft"),
            ["App.TitleBar.Page"] = new("书籍管理系统 - {0}", "NovelCraft - {0}"),
            ["App.Tagline"] = new("基于AI Agent协作的智能书籍创作平台", "An intelligent book-writing platform powered by AI Agent collaboration"),
            ["App.StartupFailed"] = new("应用程序启动失败: {0}", "Application startup failed: {0}"),
            ["App.GateCrashTitle"] = new("启动验证", "Launch Verification"),
            ["App.GateCrash"] = new("启动验证组件异常，应用已停止。详细信息见日志。", "The launch verification component failed and the application has stopped. See logs for details."),
            ["App.UnhandledErrorTitle"] = new("应用程序错误", "Application Error"),
            ["App.UnhandledError"] = new("程序遇到未处理错误，详细信息已写入日志目录，请重试或联系技术支持。", "The application encountered an unhandled error. Details have been written to the log directory. Please retry or contact technical support."),

            // ---- 通用 ----
            ["Common.CurrentPosition"] = new("当前位置：{0}", "Current: {0}"),
            ["Common.CurrentPosition.Source"] = new("当前位置：{0} · 来源：{1}", "Current: {0} · Source: {1}"),
            ["Common.NoProjectSelected"] = new("未选择项目", "No project selected"),
            ["Common.TotalWords"] = new("总字数: {0}", "Total words: {0}"),
            ["Common.ChapterCount"] = new("章节: {0}", "Chapters: {0}"),
            ["Common.RecentActivity"] = new("最近活动", "Recent Activity"),
            ["Common.NoActivity"] = new("暂无活动记录", "No recent activity"),
            ["Common.Ready"] = new("就绪", "Ready"),
            ["Common.CurrentProject"] = new("当前项目: {0}", "Current project: {0}"),
            ["Common.Version"] = new("版本 {0}", "Version {0}"),
            ["Common.Welcome"] = new("欢迎使用书籍管理系统", "Welcome to NovelCraft"),
            ["Common.QuickActions"] = new("快速操作", "Quick Actions"),
            ["Common.NewProject"] = new("新建项目", "New Project"),
            ["Common.ImportProject"] = new("导入项目", "Import Project"),
            ["Common.AICollab"] = new("AI协作", "AI Copilot"),
            ["Common.DeleteConfirm"] = new("确定删除「{0}」吗？此操作不可恢复。", "Delete \"{0}\"? This action cannot be undone."),
            ["Common.DeleteSuccess"] = new("删除成功", "Deleted successfully"),
            ["Common.SaveSuccess"] = new("保存成功", "Saved successfully"),
            ["Common.SaveFailed"] = new("保存失败：{0}", "Save failed: {0}"),
            ["Common.OperationSuccess"] = new("操作成功", "Operation succeeded"),
            ["Common.OperationFailed"] = new("操作失败：{0}", "Operation failed: {0}"),
            ["Common.LoadFailed"] = new("数据加载失败：{0}", "Failed to load data: {0}"),
            ["Common.PleaseSelectProjectFirst"] = new("请先选择一个项目", "Please select a project first"),
            ["Common.Confirm"] = new("确认", "Confirm"),
            ["Common.NotFound"] = new("未找到目标数据", "Target data not found"),
            ["Common.Items"] = new("共 {0} 条", "{0} item(s)"),

            // ---- 导航项 ----
            ["Nav.Dashboard"] = new("仪表盘", "Dashboard"),
            ["Nav.ProjectManagement"] = new("项目管理", "Project Management"),
            ["Nav.ProjectOverview"] = new("项目概览", "Project Overview"),
            ["Nav.VolumeManagement"] = new("卷宗管理", "Volumes & Chapters"),
            ["Nav.CharacterManagement"] = new("角色管理", "Character Management"),
            ["Nav.PeopleGroup"] = new("人物管理", "People"),
            ["Nav.Timeline"] = new("时间线管理", "Timeline"),
            ["Nav.RelationshipNetwork"] = new("关系网络", "Relationship Network"),
            ["Nav.FactionManagement"] = new("势力管理", "Faction Management"),
            ["Nav.PlotManagement"] = new("剧情管理", "Plot Management"),
            ["Nav.AICollaboration"] = new("AI协作创作", "AI Collaboration"),
            ["Nav.AIConfiguration"] = new("AI模型配置", "AI Model Configuration"),
            ["Nav.ImportExport"] = new("导入导出", "Import & Export"),
            ["Nav.WorldSettingManagement"] = new("世界设定", "World Settings"),
            ["Nav.SettingsGroup"] = new("设定管理", "Worldbuilding"),
            ["Nav.DialogGenerator"] = new("AI对话生成器", "Dialogue Generator"),
            ["Nav.HealthCheck"] = new("项目体检报告", "Project Health Report"),
            ["Nav.ContentManagement"] = new("内容管理", "Content Management"),
            ["Nav.StatisticsReport"] = new("统计报告", "Statistics Report"),
            ["Nav.CopilotPanel"] = new("AI 创作助手", "AI Copilot"),
            ["Nav.ProjectHealthCheck"] = new("项目体检报告", "Project Health Check Report"),
            ["STAT.Header"] = new("项目统计分析", "Project Statistics"),
            ["STAT.Section"] = new("项目统计信息", "Project Statistics"),
            ["STAT.Name"] = new("项目名称", "Project name"),
            ["STAT.Type"] = new("项目类型", "Project type"),
            ["STAT.Status"] = new("项目状态", "Project status"),
            ["STAT.LastUpdate"] = new("最后更新", "Last updated"),
            ["STAT.Volumes"] = new("卷数", "Volumes"),
            ["STAT.Chapters"] = new("章节数", "Chapters"),
            ["STAT.CompletedChapters"] = new("已完成章节", "Completed chapters"),
            ["STAT.DraftChapters"] = new("草稿章节", "Draft chapters"),
            ["STAT.Characters"] = new("角色数", "Characters"),
            ["STAT.Factions"] = new("势力数", "Factions"),
            ["STAT.Plots"] = new("剧情数", "Plots"),
            ["STAT.Settings"] = new("设定数", "Settings"),
            ["STAT.TotalWords"] = new("章节总字数", "Total chapter words"),
            ["STAT.AvgChapterWords"] = new("平均章节字数", "Avg words per chapter"),
            ["STAT.AvgVolumeWords"] = new("平均卷字数", "Avg words per volume"),
            ["STAT.WordsFmt"] = new("{0} 字", "{0} words"),
            ["STAT.TitleFmt"] = new("项目统计分析 - {0}", "Project Statistics - {0}"),
            ["STAT.Notes"] = new("说明：", "Notes:"),
            ["STAT.Note1"] = new("当前统计入口已统一接入项目统计聚合服务", "Statistics are aggregated by the unified project statistics service"),
            ["STAT.Note2"] = new("后续可继续扩展创作趋势、AI 使用、结构质量等更细分报表", "More reports (writing trends, AI usage, structure quality) are planned"),

            // ---- 仪表盘 ----
            ["Dash.ProjectOverview"] = new("项目概览", "Project Overview"),
            ["Dash.OpenProject"] = new("打开项目", "Open Project"),
            ["Dash.TitleBar"] = new("书籍管理系统 - 仪表盘", "NovelCraft - Dashboard"),
            ["Dash.CurrentPosition"] = new("当前位置：仪表盘", "Current: Dashboard"),
            ["Dash.ChipInProgress"] = new("进行中", "In Progress"),
            ["Dash.DemoTotalWords"] = new("总字数: 125,000", "Total words: 125,000"),
            ["Dash.DemoChapters"] = new("章节: 45", "Chapters: 45"),
            ["Dash.CurrentProjectNone"] = new("当前项目: 未选择", "Current project: none"),
            ["Dash.VersionText"] = new("版本 1.0.1", "Version 1.0.1"),

            // ---- 主窗口框架 ----
            ["Shell.Tip.Back"] = new("返回上一页", "Back"),
            ["Shell.Tip.Copilot"] = new("AI 创作助手（对话式创作）", "AI Copilot (conversational writing)"),
            ["Shell.Tip.Theme"] = new("主题配置与皮肤设定", "Theme & skin settings"),
            ["Shell.Tip.Language"] = new("切换语言（中文 / English）", "Switch language (中文 / English)"),
            ["Shell.Tip.AIConfig"] = new("AI模型配置与设置", "AI model configuration"),
            ["Shell.Tip.Help"] = new("帮助", "Help"),

            // ---- 侧栏 ----
            ["Side.Group.AIAssistant"] = new("AI助手", "AI Assistant"),
            ["Side.Btn.OneClick"] = new("一键生成书籍", "One-Click Book Generation"),
            ["Side.Btn.BatchGenerate"] = new("长篇批量生成", "Long-Form Batch Generation"),
            ["Side.Btn.GenerateProgress"] = new("生成进度", "Generation Progress"),
            ["Side.Btn.Prerequisite"] = new("前置条件生成", "Prerequisite Generation"),
            ["Side.Btn.DialogGen"] = new("对话生成器", "Dialogue Generator"),
            ["Side.Btn.ContentGen"] = new("内容生成", "Content Generation"),
            ["Side.Btn.QualityCheck"] = new("质量检查", "Quality Check"),
            ["Side.Btn.Consistency"] = new("一致性检查", "Consistency Check"),
            ["Side.Btn.ExportProject"] = new("导出项目", "Export Project"),
            ["Side.Btn.Publish"] = new("发布管理", "Publishing Management"),
            ["Side.Btn.Timeline"] = new("时间线", "Timeline"),
            ["Side.Btn.Population"] = new("生民体系", "Population System"),
            ["TT.OneClick"] = new("由 RWKV 双 Agent 自动命名新书并生成大纲与第一章", "RWKV dual-Agent auto-names a new book and generates the synopsis and first chapter"),
            ["TT.BatchGenerate"] = new("RWKV 官方创意参数 + 切片创作：3卷×30章×每章≥3000字，后台运行，支持断点续跑", "RWKV official creative parameters + sliced writing: 3 volumes x 30 chapters x >=3000 words each. Runs in background with resumable progress"),
            ["TT.GenerateProgress"] = new("查看整本长篇批量生成任务的当前进度与评分", "View current progress and scores of the long-form batch generation"),
            ["TT.Prerequisite"] = new("为AI编辑功能生成必要的前置数据", "Generate prerequisite data for AI editing features"),

            // ---- 主窗口代码层（MainWindow / OperationsManagementWindow，MW.*）----
            ["MW.OpenFailed"] = new("打开{0}失败：{1}", "Failed to open {0}: {1}"),
            ["MW.LoadViewFailed"] = new("加载{0}界面失败：{1}", "Failed to load the {0} view: {1}"),
            ["MW.LoadAIViewFailed"] = new("加载AI协作界面失败：{0}\n\n详细信息：{1}", "Failed to load the AI collaboration view: {0}\n\nDetails: {1}"),
            ["MW.CreateProjectFailed"] = new("创建项目失败：{0}", "Failed to create project: {0}"),
            ["MW.ImportFailed"] = new("导入项目失败：{0}", "Failed to import project: {0}"),
            ["MW.ImportedFrom"] = new("从文件 {0} 导入的项目", "Project imported from file {0}"),
            ["MW.ImportFilter"] = new("项目文件|*.npj;*.json|JSON文件|*.json|所有文件|*.*", "Project files|*.npj;*.json|JSON files|*.json|All files|*.*"),
            ["MW.OpenPageFailed"] = new("打开项目页面失败：{0}", "Failed to open project page: {0}"),
            ["MW.ErrorDetail"] = new("详细信息：{0}", "Details: {0}"),
            ["MW.OpsWindowNotInit"] = new("运维管理窗口未初始化", "The operations management window is not initialized"),
            ["MW.OpenOpsFailed"] = new("打开发布与运维管理失败：{0}", "Failed to open publishing & operations management: {0}"),
            ["MW.StatisticsServiceNotInit"] = new("项目统计服务未初始化", "The project statistics service is not initialized"),
            ["MW.ProjectNotFound"] = new("未找到当前项目，请重新选择项目。", "Current project not found. Please select a project again."),
            ["MW.ProjectGuardNotInit"] = new("项目校验服务未初始化", "The current-project guard service is not initialized"),
            ["MW.HelpTitle"] = new("使用帮助", "Help"),
            ["MW.HelpText"] = new("常用入口说明：\n1. 左侧导航用于项目、人物、设定、AI 协作等功能切换。\n2. 右上角齿轮用于打开 AI 模型配置中心。\n3. AI 模型配置会保存到当前用户的本地配置目录，不会覆盖发布目录。\n4. 修改模型配置后，部分选项需要重启应用才会完全生效。\n\n如果某个页面打不开，请把完整弹窗内容发给我继续修复。", "Quick reference:\n1. Use the left navigation to switch between projects, characters, worldbuilding, AI collaboration, and more.\n2. The gear icon at the top right opens the AI model configuration center.\n3. AI model configuration is saved to the current user's local config directory and does not overwrite the publish directory.\n4. After changing the model configuration, some options require an app restart to take full effect.\n\nIf a page fails to open, send me the full dialog content so I can keep fixing it."),
            ["MW.AIGenFileTitle"] = new("AI内容生成", "AI Content Generation"),
            ["MW.ShowPrereqDialogFailed"] = new("显示前置条件生成对话框失败：{0}", "Failed to show the prerequisite generation dialog: {0}"),
            ["MW.OneClickServiceMissing"] = new("一键生成服务未注册", "The one-click generation service is not registered"),
            ["MW.OneClickFailed"] = new("一键生成失败：{0}", "One-click generation failed: {0}"),
            ["MW.OneClickDone"] = new("一键生成完成", "One-click generation completed"),
            ["MW.Preparing"] = new("准备中...", "Preparing..."),
            ["MW.BatchServiceMissing"] = new("长篇批量生成服务未注册", "The long-form batch generation service is not registered"),
            ["MW.BatchAlreadyRunning"] = new("批量生成任务已在运行中，可用「生成进度」按钮查看。", "A batch generation task is already running. Use the \"Generation Progress\" button to view it."),
            ["MW.BatchModeUnlimited"] = new("无限续写模式", "Unlimited continuation mode"),
            ["MW.BatchModeQuickSwitch"] = new("快速切卷（每卷 3 章后切新卷）", "Quick volume switch (new volume after every 3 chapters)"),
            ["MW.BatchModeStandard"] = new("标准模式", "Standard mode"),
            ["MW.BatchModeSuffix"] = new("，每卷 {0} 章", ", {0} chapters per volume"),
            ["MW.BatchConfirm"] = new("将启动长篇批量生成：{0} × 每章 ≥{1} 字。\n采样采用 RWKV 官方创意参数 + DRY 抗复读采样，\n章节正文使用“切片创作 + 拼接”工艺（16K 上下文限制）。\n\n任务在后台运行，期间可正常使用软件其他功能。\n若存在未完成的批量任务将自动从断点继续。\n\n确定开始？", "Long-form batch generation will start: {0} x >= {1} words per chapter.\nSampling uses RWKV official creative parameters + DRY anti-repetition sampling.\nChapter content uses the \"sliced writing + stitching\" process (16K context limit).\n\nThe task runs in the background; you can keep using other app features meanwhile.\nIf an unfinished batch task exists, it will automatically resume from the checkpoint.\n\nStart now?"),
            ["MW.Started"] = new("已启动", "Started"),
            ["MW.BatchStartFailed"] = new("启动批量生成失败：{0}", "Failed to start batch generation: {0}"),
            ["MW.BatchProgressTitle"] = new("长篇批量生成进度", "Long-Form Batch Generation Progress"),
            ["MW.StatusLine"] = new("状态：{0}", "Status: {0}"),
            ["MW.BatchStatusRunning"] = new("运行中", "Running"),
            ["MW.BatchStatusNotRunning"] = new("未运行", "Not running"),
            ["MW.PhaseLine"] = new("阶段：{0}", "Phase: {0}"),
            ["MW.BookTitleLine"] = new("书名：{0}", "Book title: {0}"),
            ["MW.SpecLine"] = new("规格：{0} 卷 × {1} 章", "Spec: {0} volumes x {1} chapters"),
            ["MW.PositionLine"] = new("位置：第 {0} 卷 第 {1} 章", "Position: volume {0}, chapter {1}"),
            ["MW.DoneFailedLine"] = new("已完成：{0} 章，失败：{1} 章", "Completed: {0} chapters, failed: {1} chapters"),
            ["MW.LastScoreLine"] = new("最近章节评分：{0:F1}/10", "Latest chapter score: {0:F1}/10"),
            ["MW.LastMessageLine"] = new("最近消息：{0}", "Latest message: {0}"),
            ["MW.LastErrorLine"] = new("最近错误：{0}", "Latest error: {0}"),
            ["MW.StartedLine"] = new("开始时间：{0:HH:mm:ss}，已运行 {1:F0} 分钟", "Started at {0:HH:mm:ss}, running for {1:F0} min"),
            ["MW.NoSelection"] = new("未选择", "None"),
            ["MW.CurrentOpenProject"] = new("当前打开的项目", "Currently open project"),
            ["MW.ActivityProjectUpdated"] = new("项目《{0}》有内容更新", "Project \"{0}\" has new content updates"),
            ["MW.ActivityChapterUpdated"] = new("更新了章节：{0}", "Updated chapter: {0}"),
            ["MW.ActivityCharacterUpdated"] = new("角色资料更新：{0}", "Character profile updated: {0}"),
            ["MW.TimeJustNow"] = new("刚刚", "Just now"),
            ["MW.TimeMinutesAgo"] = new("{0}分钟前", "{0} min ago"),
            ["MW.TimeHoursAgo"] = new("{0}小时前", "{0} h ago"),
            ["MW.TimeDaysAgo"] = new("{0}天前", "{0} d ago"),

            // ---- 运维窗口（OperationsManagementWindow）----
            ["MW.OpsTitle"] = new("发布与运维管理", "Publishing & Operations"),
            ["MW.LoadingHealth"] = new("正在加载健康检查...", "Loading health check..."),
            ["MW.BtnRefreshHealth"] = new("刷新健康检查", "Refresh Health Check"),
            ["MW.BtnBackupNow"] = new("立即备份数据库", "Back Up Database Now"),
            ["MW.BtnRestore"] = new("从备份恢复数据库", "Restore from Backup"),
            ["MW.BtnExportDiagnostics"] = new("导出诊断包", "Export Diagnostic Bundle"),
            ["MW.BtnOpenDataDir"] = new("打开数据目录", "Open Data Directory"),
            ["MW.BtnOpenLogsDir"] = new("打开日志目录", "Open Logs Directory"),
            ["MW.BtnOpenBackupsDir"] = new("打开备份目录", "Open Backups Directory"),
            ["MW.BtnReopenOnboarding"] = new("重新打开首次向导", "Reopen First-Run Wizard"),
            ["MW.BtnChangePassword"] = new("修改启动密码", "Change Launch Password"),
            ["MW.DirData"] = new("数据目录", "Data directory"),
            ["MW.DirLogs"] = new("日志目录", "Logs directory"),
            ["MW.DirBackups"] = new("备份目录", "Backups directory"),
            ["MW.HealthSummary"] = new("系统状态: {0}    生成时间: {1:yyyy-MM-dd HH:mm:ss}", "System status: {0}    Generated at: {1:yyyy-MM-dd HH:mm:ss}"),
            ["MW.HealthFailedSummary"] = new("系统状态: 健康检查失败", "System status: health check failed"),
            ["MW.HealthFailedDetail"] = new("健康检查失败:{0}{1}", "Health check failed:{0}{1}"),
            ["MW.BackupFailed"] = new("数据库备份失败", "Database backup failed"),
            ["MW.BackupFailedTitle"] = new("备份失败", "Backup Failed"),
            ["MW.BackupFailedWithReason"] = new("数据库备份失败：{0}", "Database backup failed: {0}"),
            ["MW.BackupDone"] = new("数据库备份已完成：{0}{1}", "Database backup completed:{0}{1}"),
            ["MW.BackupDoneTitle"] = new("备份成功", "Backup Completed"),
            ["MW.RestoreDialogTitle"] = new("选择要恢复的数据库备份", "Select a database backup to restore"),
            ["MW.FilterSQLite"] = new("SQLite 数据库|*.db|所有文件|*.*", "SQLite database|*.db|All files|*.*"),
            ["MW.RestoreConfirm"] = new("恢复数据库将覆盖当前数据库文件。系统会先自动为当前数据库创建一个恢复前备份。恢复完成后建议立即重启应用。\n\n是否继续？", "Restoring the database will overwrite the current database file. The system will first automatically create a pre-restore backup of the current database. After the restore completes, it is recommended to restart the app immediately.\n\nContinue?"),
            ["MW.RestoreConfirmTitle"] = new("确认恢复", "Confirm Restore"),
            ["MW.PreRestoreFailed"] = new("恢复前备份失败", "Pre-restore backup failed"),
            ["MW.RestoreFailedTitle"] = new("恢复失败", "Restore Failed"),
            ["MW.RestoreFailed"] = new("数据库恢复失败", "Database restore failed"),
            ["MW.RestoreFailedWithReason"] = new("数据库恢复失败：{0}", "Database restore failed: {0}"),
            ["MW.RestoreDone"] = new("数据库恢复成功：{0}{1}{2}{2}恢复前备份：{3}{2}{2}请重启应用以重新加载数据库。", "Database restored successfully:{0}{1}{2}{2}Pre-restore backup:{3}{2}{2}Please restart the app to reload the database."),
            ["MW.RestoreDoneTitle"] = new("恢复成功", "Restore Completed"),
            ["MW.FilterZip"] = new("ZIP 文件|*.zip", "ZIP files|*.zip"),
            ["MW.ExportFailed"] = new("诊断包导出失败", "Failed to export diagnostic bundle"),
            ["MW.ExportFailedTitle"] = new("导出失败", "Export Failed"),
            ["MW.ExportFailedWithReason"] = new("导出诊断包失败：{0}", "Failed to export diagnostic bundle: {0}"),
            ["MW.ExportDone"] = new("诊断包已导出：{0}{1}", "Diagnostic bundle exported:{0}{1}"),
            ["MW.ExportDoneTitle"] = new("导出成功", "Export Completed"),
            ["MW.OnboardingNotInit"] = new("首次启动向导未初始化", "The first-run wizard is not initialized"),
            ["MW.OpenOnboardingFailed"] = new("打开首次启动向导失败：{0}", "Failed to open the first-run wizard: {0}"),
            ["MW.OpenChangePwdFailed"] = new("打开修改启动密码对话框失败：{0}", "Failed to open the change-password dialog: {0}"),
            ["MW.DirNotExist"] = new("{0}不存在", "{0} does not exist"),
            ["MW.ReportTitle"] = new("发布与运维健康检查报告", "Publishing & Operations Health Check Report"),
            ["MW.ReportOverall"] = new("总体状态: {0}", "Overall status: {0}"),
            ["MW.ReportAppDataRoot"] = new("应用数据根目录: {0}", "App data root: {0}"),
            ["MW.ReportDbFile"] = new("数据库文件: {0}", "Database file: {0}"),
            ["MW.ReportLogsDir"] = new("日志目录: {0}", "Logs directory: {0}"),
            ["MW.ReportBackupsDir"] = new("备份目录: {0}", "Backups directory: {0}"),
            ["MW.ReportItemsHeader"] = new("检查项明细:", "Check item details:"),
            ["MW.StatusHealthy"] = new("健康", "Healthy"),
            ["MW.StatusUnhealthy"] = new("异常", "Unhealthy"),

            // ---- 体系页窗口标题（World.*.Title）----
            ["World.Cultivation.Title"] = new("修炼体系管理", "Cultivation System"),
            ["World.Political.Title"] = new("政治体系管理", "Political System"),
            ["World.Profession.Title"] = new("职业体系管理", "Profession System"),
            ["World.Judicial.Title"] = new("司法体系管理", "Judicial System"),
            ["World.Population.Title"] = new("生民体系管理", "Population System"),
            ["World.Treasure.Title"] = new("灵宝体系管理", "Treasure System"),
            ["World.Dimension.Title"] = new("维度结构管理", "Dimension Structure"),
            ["World.Map.Title"] = new("地图结构管理", "Map Structure"),
            ["World.Pet.Title"] = new("宠物体系管理", "Pet System"),
            ["World.Equipment.Title"] = new("装备体系管理", "Equipment System"),
            ["World.Technique.Title"] = new("功法体系管理", "Technique System"),
            ["World.Business.Title"] = new("商业体系管理", "Business System"),

            // ---- 批次G2 补充词条（G2 run1 未落盘补齐） ----
            ["MW.ActivityProjectUpdated"] = new("项目《{0}》有内容更新", "Project \"{0}\" has content updates"),
            ["MW.BatchAlreadyRunning"] = new("批量生成任务已在运行中，可用「生成进度」按钮查看。", "A batch generation task is already running; use the \"Generation Progress\" button to view it."),
            ["MW.BatchConfirm"] = new("将启动长篇批量生成：{0} × 每章 ≥{1} 字。\n采样采用 RWKV 官方创意参数 + DRY 抗复读采样，\n章节正文使用“切片创作 + 拼接”工艺（16K 上下文限制）。\n\n任务在后台运行，期间可正常使用软件其他功能。\n若存在未完成的批量任务将自动从断点继续。\n\n确定开始？", "Starting long-form batch generation: {0} × ≥{1} characters per chapter.\nSampling uses RWKV official creative parameters + DRY anti-repetition sampling.\nChapter text uses the \"slice-writing + stitching\" pipeline (16K context limit).\n\nThe task runs in the background; other features remain usable meanwhile.\nIf an unfinished batch task exists, it will automatically resume from the breakpoint.\n\nStart now?"),
        };
    }
}
