using System.Collections.Generic;

namespace NovelManagement.WPF.Localization
{
    /// <summary>
    /// 词条表：运维（导入导出/体检/发布运维/密码门/主题设置/首启引导/进度与结果对话框）。
    /// 键前缀约定：IE.* 导入导出；HC.* 体检；OM.* 运维窗口；PGate.* 密码门；CPW.* 改密；TS.* 主题设置；FO.* 首启引导；PD.* 进度对话框；AR.* 分析结果；CM2.* 一致性检查对话框。
    /// </summary>
    internal static class StringsOperations
    {
        internal static readonly IReadOnlyDictionary<string, LocEntry> Entries = new Dictionary<string, LocEntry>
        {
            #region 密码门（PGate.*）
            ["PGate.Title"] = new("启动验证", "Launch Verification"),
            ["PGate.WindowTitle"] = new("书籍管理系统 - 启动验证", "NovelCraft - Launch Verification"),
            ["PGate.AppName"] = new("书籍管理系统", "NovelCraft"),
            ["PGate.Subtitle"] = new("请输入启动密码以继续", "Enter the launch password to continue"),
            ["PGate.Verify"] = new("确 定", "Confirm"),
            ["PGate.Cancel"] = new("取 消", "Cancel"),
            ["PGate.WrongPassword"] = new("密码错误，请重新输入", "Incorrect password. Please try again"),
            #endregion

            #region 导入导出（IE.*）
            ["IE.PageTitle"] = new("导入导出管理", "Import & Export Management"),
            ["IE.PageSubtitle"] = new("管理项目数据的导入导出，支持多种格式和批量操作", "Manage import and export of project data, with multiple formats and batch operations"),
            ["IE.ExportTab"] = new("导出管理", "Export"),
            ["IE.ExportConfig"] = new("导出配置", "Export Settings"),
            ["IE.ExportFormat"] = new("导出格式", "Export Format"),
            ["IE.FmtTxt"] = new("TXT - 纯文本格式", "TXT - Plain Text"),
            ["IE.FmtExcel"] = new("EXCEL - Excel表格格式", "EXCEL - Excel Spreadsheet"),
            ["IE.FmtDocx"] = new("DOCX - Word文档格式", "DOCX - Word Document"),
            ["IE.FmtHtml"] = new("HTML - 网页格式", "HTML - Web Page"),
            ["IE.FmtMarkdown"] = new("MARKDOWN - Markdown格式", "MARKDOWN - Markdown"),
            ["IE.FmtJson"] = new("JSON - JSON数据格式", "JSON - JSON Data"),
            ["IE.ExportScope"] = new("导出范围", "Export Scope"),
            ["IE.ScopeEntireProject"] = new("整个项目", "Entire Project"),
            ["IE.ScopeSelectedVolumes"] = new("选定卷宗", "Selected Volumes"),
            ["IE.ScopeSelectedChapters"] = new("选定章节", "Selected Chapters"),
            ["IE.ScopeCustomRange"] = new("自定义范围", "Custom Range"),
            ["IE.SelectItems"] = new("选择项目", "Select Items"),
            ["IE.SampleVolume1"] = new("第一卷 - 初入仙途", "Volume 1 - Entering the Path"),
            ["IE.SampleVolume2"] = new("第二卷 - 风云际会", "Volume 2 - Gathering Storms"),
            ["IE.SampleVolume3"] = new("第三卷 - 天地争锋", "Volume 3 - Clash of Heaven and Earth"),
            ["IE.IncludeContent"] = new("包含内容", "Include Content"),
            ["IE.IncludeSettings"] = new("设定信息", "Settings Info"),
            ["IE.IncludeCharacters"] = new("角色信息", "Character Info"),
            ["IE.IncludeFactions"] = new("势力信息", "Faction Info"),
            ["IE.IncludePlots"] = new("剧情信息", "Plot Info"),
            ["IE.OutputPath"] = new("输出路径", "Output Path"),
            ["IE.OutputPathHint"] = new("选择输出文件路径", "Choose the output file path"),
            ["IE.BrowseFolder"] = new("浏览文件夹", "Browse Folder"),
            ["IE.StartExport"] = new("开始导出", "Start Export"),
            ["IE.ExportProgress"] = new("导出进度", "Export Progress"),
            ["IE.CancelExport"] = new("取消导出", "Cancel Export"),
            ["IE.Preparing"] = new("准备中...", "Preparing..."),
            ["IE.ItemsProcessed0"] = new("0 / 0 项目已处理", "0 / 0 items processed"),
            ["IE.ItemsProcessedFmt"] = new("{0} / {1} 项目已处理", "{0} / {1} items processed"),
            ["IE.ExportHistory"] = new("导出历史", "Export History"),
            ["IE.RefreshHistory"] = new("刷新历史记录", "Refresh History"),
            ["IE.OpenFile"] = new("打开文件", "Open File"),
            ["IE.OpenFolder"] = new("打开文件夹", "Open Folder"),
            ["IE.ImportTab"] = new("导入管理", "Import"),
            ["IE.ImportConfig"] = new("导入配置", "Import Settings"),
            ["IE.SelectFile"] = new("选择文件", "Select File"),
            ["IE.ImportFileHint"] = new("选择要导入的文件", "Choose the file to import"),
            ["IE.BrowseFile"] = new("浏览文件", "Browse File"),
            ["IE.FileFormat"] = new("文件格式", "File Format"),
            ["IE.FmtExcelFile"] = new("EXCEL - Excel表格文件", "EXCEL - Excel Spreadsheet File"),
            ["IE.FmtDocxFile"] = new("DOCX - Word文档文件", "DOCX - Word Document File"),
            ["IE.FmtCsvFile"] = new("CSV - 逗号分隔值文件", "CSV - Comma-Separated Values File"),
            ["IE.FmtTxtFile"] = new("TXT - 纯文本文件", "TXT - Plain Text File"),
            ["IE.FmtJsonFile"] = new("JSON - JSON数据文件", "JSON - JSON Data File"),
            ["IE.FmtXmlFile"] = new("XML - XML数据文件", "XML - XML Data File"),
            ["IE.ImportOptions"] = new("导入选项", "Import Options"),
            ["IE.OverwriteExisting"] = new("覆盖现有数据", "Overwrite Existing Data"),
            ["IE.CreateBackup"] = new("创建备份", "Create Backup"),
            ["IE.PreviewFile"] = new("预览文件", "Preview File"),
            ["IE.StartImport"] = new("开始导入", "Start Import"),
            ["IE.ImportProgress"] = new("导入进度", "Import Progress"),
            ["IE.CancelImport"] = new("取消导入", "Cancel Import"),
            ["IE.ImportHistory"] = new("导入历史", "Import History"),
            ["IE.ViewDetails"] = new("查看详情", "View Details"),
            ["IE.FeatureName"] = new("导入导出", "Import & Export"),
            ["IE.InitFailed"] = new("初始化失败: {0}", "Initialization failed: {0}"),
            ["IE.SaveDialogTitle"] = new("选择导出文件保存位置", "Choose Where to Save the Export File"),
            ["IE.FilterAll"] = new("所有支持的格式", "All Supported Formats"),
            ["IE.FilterTxt"] = new("文本文件", "Text Files"),
            ["IE.FilterExcel"] = new("Excel文件", "Excel Files"),
            ["IE.FilterWord"] = new("Word文档", "Word Documents"),
            ["IE.FilterHtml"] = new("网页文件", "Web Pages"),
            ["IE.FilterMarkdown"] = new("Markdown文件", "Markdown Files"),
            ["IE.FilterJson"] = new("JSON文件", "JSON Files"),
            ["IE.DefaultExportFolder"] = new("书籍导出", "Book Exports"),
            ["IE.DefaultExportFileName"] = new("千面劫·宿命轮回", "My Novel"),
            ["IE.FilterCsv"] = new("CSV文件", "CSV Files"),
            ["IE.FilterXml"] = new("XML文件", "XML Files"),
            ["IE.SelectOutputPath"] = new("请选择输出文件路径", "Please choose the output file path"),
            ["IE.SelectFormatAndScope"] = new("请选择导出格式和范围", "Please choose the export format and scope"),
            ["IE.SelectExportItems"] = new("请选择要导出的项目", "Please select the items to export"),
            ["IE.StartExportFailed"] = new("启动导出失败: {0}", "Failed to start export: {0}"),
            ["IE.FileNotFound"] = new("文件不存在", "File not found"),
            ["IE.OpenFileFailed"] = new("打开文件失败: {0}", "Failed to open the file: {0}"),
            ["IE.FolderNotFound"] = new("文件夹不存在", "Folder not found"),
            ["IE.OpenFolderFailed"] = new("打开文件夹失败: {0}", "Failed to open the folder: {0}"),
            ["IE.SelectPreviewFile"] = new("请选择要预览的文件", "Please choose the file to preview"),
            ["IE.SelectFileFormat"] = new("请选择文件格式", "Please choose the file format"),
            ["IE.PreviewFailed"] = new("预览文件失败: {0}", "Failed to preview the file: {0}"),
            ["IE.SelectImportFileMsg"] = new("请选择要导入的文件", "Please choose the file to import"),
            ["IE.StartImportFailed"] = new("启动导入失败: {0}", "Failed to start import: {0}"),
            ["IE.DetailsOpId"] = new("操作ID: {0}", "Operation ID: {0}"),
            ["IE.DetailsFormat"] = new("格式: {0}", "Format: {0}"),
            ["IE.DetailsFile"] = new("文件: {0}", "File: {0}"),
            ["IE.DetailsSize"] = new("大小: {0:N0} 字节", "Size: {0:N0} bytes"),
            ["IE.DetailsStatus"] = new("状态: {0}", "Status: {0}"),
            ["IE.DetailsStartTime"] = new("开始时间: {0}", "Start time: {0}"),
            ["IE.DetailsEndTime"] = new("完成时间: {0}", "End time: {0}"),
            ["IE.NotCompleted"] = new("未完成", "Not completed"),
            ["IE.DetailsNotes"] = new("备注: {0}", "Notes: {0}"),
            ["IE.None"] = new("无", "None"),
            ["IE.ImportDetails"] = new("导入详情", "Import Details"),
            ["IE.StatusPending"] = new("等待中", "Pending"),
            ["IE.StatusInProgress"] = new("进行中", "In Progress"),
            ["IE.StatusCompleted"] = new("已完成", "Completed"),
            ["IE.StatusFailed"] = new("已失败", "Failed"),
            ["IE.StatusCancelled"] = new("已取消", "Cancelled"),
            ["IE.StatusUnknown"] = new("未知", "Unknown"),
            ["IE.ExportSuccessTitle"] = new("导出成功", "Export Succeeded"),
            ["IE.ExportDone"] = new("导出完成！\n文件保存在: {0}", "Export completed!\nFile saved at: {0}"),
            ["IE.ExportFailedTitle"] = new("导出失败", "Export Failed"),
            ["IE.ExportFailedMsg"] = new("导出失败: {0}", "Export failed: {0}"),
            ["IE.ImportSuccessTitle"] = new("导入成功", "Import Succeeded"),
            ["IE.ImportDone"] = new("导入完成！\n处理了 {0} 条记录", "Import completed!\n{0} records processed"),
            ["IE.WarningsLine"] = new("警告: {0}", "Warnings: {0}"),
            ["IE.ImportFailedTitle"] = new("导入失败", "Import Failed"),
            ["IE.ImportFailedMsg"] = new("导入失败: {0}", "Import failed: {0}"),
            ["IE.PreviewFileInfo"] = new("文件信息:", "File information:"),
            ["IE.PreviewFileName"] = new("文件名: {0}", "File name: {0}"),
            ["IE.PreviewRecordCount"] = new("记录数: {0}", "Record count: {0}"),
            ["IE.PreviewDetectedTypes"] = new("检测到的数据类型: {0}", "Detected data types: {0}"),
            ["IE.PreviewFieldsHeader"] = new("字段信息:", "Field information:"),
            ["IE.PreviewTitle"] = new("文件预览", "File Preview"),
            #endregion

            #region 项目体检（HC.*）
                        ["HC.Rpt.AppDataDir"] = new("应用数据目录", "App data directory"),
            ["HC.Rpt.ConfigDir"] = new("配置目录", "Config directory"),
            ["HC.Rpt.DataDir"] = new("数据目录", "Data directory"),
            ["HC.Rpt.LogsDir"] = new("日志目录", "Logs directory"),
            ["HC.Rpt.BackupsDir"] = new("备份目录", "Backups directory"),
            ["HC.Rpt.DbFile"] = new("数据库文件", "Database file"),
            ["HC.Rpt.DbFileFound"] = new("已找到数据库文件: {0}", "Database file found: {0}"),
            ["HC.Rpt.DbFileMissing"] = new("未找到数据库文件: {0}", "Database file not found: {0}"),
            ["HC.Rpt.UserConfig"] = new("用户覆盖配置", "User override config"),
            ["HC.Rpt.UserConfigFound"] = new("已找到用户配置: {0}", "User config found: {0}"),
            ["HC.Rpt.UserConfigMissing"] = new("未找到用户配置: {0}", "User config not found: {0}"),
            ["HC.Rpt.DbBackup"] = new("数据库备份", "Database backup"),
            ["HC.Rpt.BackupsAvailable"] = new("当前可用备份数量: {0}", "Available backups: {0}"),
            ["HC.Rpt.NoBackupYet"] = new("当前尚无数据库备份文件", "No database backup yet"),
            ["HC.Rpt.RuntimeEnv"] = new("运行环境", "Runtime environment"),
            ["HC.Rpt.CurrentEnv"] = new("当前环境: {0}", "Current environment: {0}"),
            ["HC.Rpt.ConfigValidationFmt"] = new("配置校验 / {0}", "Config validation / {0}"),
            ["HC.Rpt.PathMissing"] = new("路径配置缺失", "Path configuration missing"),
            ["HC.Rpt.DirExists"] = new("目录存在: {0}", "Directory exists: {0}"),
            ["HC.Rpt.DirMissing"] = new("目录不存在: {0}", "Directory does not exist: {0}"),
            ["HC.Rpt.DbConnection"] = new("数据库连接", "Database connection"),
            ["HC.Rpt.DbOk"] = new("数据库连接正常", "Database connection OK"),
            ["HC.Rpt.DbFail"] = new("数据库连接失败", "Database connection failed"),
            ["HC.Rpt.DbMigrations"] = new("数据库迁移", "Database migrations"),
            ["HC.Rpt.NoMigrations"] = new("没有待处理迁移", "No pending migrations"),
            ["HC.Rpt.PendingMigrations"] = new("存在 {0} 个待处理迁移", "{0} pending migration(s)"),
            ["HC.Rpt.DbHealthCheck"] = new("数据库健康检查", "Database health check"),
            ["HC.Rpt.CheckFailed"] = new("检查失败: {0}", "Check failed: {0}"),
            ["HC.Rpt.AiConnectivity"] = new("AI 连通性检测", "AI connectivity check"),
            ["HC.Val.AppDataRoot"] = new("应用数据根目录", "App data root directory"),
            ["HC.Val.ConfigDir"] = new("配置目录", "Config directory"),
            ["HC.Val.DataDir"] = new("数据目录", "Data directory"),
            ["HC.Val.LogsDir"] = new("日志目录", "Logs directory"),
            ["HC.Val.BackupsDir"] = new("备份目录", "Backups directory"),
            ["HC.Val.UserConfigFile"] = new("用户覆盖配置文件", "User override config file"),
            ["HC.Val.AppEnv"] = new("应用环境", "Application environment"),
            ["HC.Val.BackupRetention"] = new("备份保留策略", "Backup retention policy"),
            ["HC.Val.AiToggle"] = new("AI 功能开关", "AI feature toggle"),
            ["HC.Val.OllamaCfg"] = new("Ollama 配置", "Ollama configuration"),
            ["HC.Val.RwkvCfg"] = new("RWKV 配置", "RWKV configuration"),
            ["HC.Val.DeepSeekCfg"] = new("DeepSeek 配置", "DeepSeek configuration"),
            ["HC.Val.ZhipuCfg"] = new("智谱 AI 配置", "Zhipu AI configuration"),
            ["HC.Val.ZhipuName"] = new("智谱AI", "Zhipu AI"),
            ["HC.Val.OpenAiCfg"] = new("OpenAI 兼容配置", "OpenAI-compatible configuration"),
            ["HC.Val.MsgDirMissing"] = new("目录不存在，将在运行时尝试创建: {0}", "Directory missing; will attempt to create at runtime: {0}"),
            ["HC.Val.MsgUserConfigFound"] = new("已发现用户覆盖配置: {0}", "User override config found: {0}"),
            ["HC.Val.MsgUserConfigMissing"] = new("未发现用户覆盖配置: {0}", "User override config not found: {0}"),
            ["HC.Val.MsgEnvProd"] = new("当前环境为 {0}", "Current environment: {0}"),
            ["HC.Val.MsgEnvNonProd"] = new("当前环境为 {0}，生产部署建议使用 Production", "Current environment: {0}; use Production for production deployment"),
            ["HC.Val.MsgRetentionOk"] = new("备份保留天数: {0}", "Backup retention days: {0}"),
            ["HC.Val.MsgRetentionInvalid"] = new("备份保留天数必须大于 0", "Backup retention days must be greater than 0"),
            ["HC.Val.MsgAiDisabled"] = new("AI 功能当前已关闭", "AI features are currently disabled"),
            ["HC.Val.MsgAiEnabled"] = new("AI 功能已启用", "AI features are enabled"),
            ["HC.Val.MsgAiSkipped"] = new("AI 功能已关闭，跳过连通性检测", "AI features disabled; connectivity checks skipped"),
            ["HC.Val.MsgConfigValid"] = new("配置合法", "Configuration is valid"),
            ["HC.Val.MsgConnOkMs"] = new("连接成功，响应时间 {0} ms", "Connected, responded in {0} ms"),
            ["HC.Val.MsgConnOk"] = new("连接成功", "Connected"),
            ["HC.Val.MsgConnFail"] = new("连接失败", "Connection failed"),
            ["HC.Val.MsgConnFailOrNotRunning"] = new("连接失败或服务未启动", "Connection failed or service not running"),
            ["HC.Val.MsgCfgIncomplete"] = new("配置不完整: {0}", "Incomplete configuration: {0}"),
["HC.Title"] = new("项目体检报告", "Project Health Check Report"),
            ["HC.MsgTitle"] = new("项目体检", "Project Health Check"),
            ["HC.SelectProjectFirst"] = new("请先选择项目", "Select a project first"),
            ["HC.ConsistencyCheck"] = new("一致性检查", "Consistency Check"),
            ["HC.QualityCheck"] = new("质量检查", "Quality Check"),
            ["HC.FullCheck"] = new("全部检查", "Full Check"),
            ["HC.Recheck"] = new("复检", "Re-check"),
            ["HC.ErrorCount0"] = new("错误 0", "Errors: 0"),
            ["HC.WarningCount0"] = new("警告 0", "Warnings: 0"),
            ["HC.InfoCount0"] = new("提示 0", "Info: 0"),
            ["HC.NotCheckedYet"] = new("尚未检查", "Not checked yet"),
            ["HC.ResultsHeader"] = new("检查结果（已按严重级别排序）", "Check Results (sorted by severity)"),
            ["HC.IssueCount0"] = new("0 个问题", "0 issues"),
            ["HC.IssueCountFmt"] = new("{0} 个问题", "{0} issue(s)"),
            ["HC.ColSeverity"] = new("级别", "Severity"),
            ["HC.ColCategory"] = new("分类", "Category"),
            ["HC.ColDescription"] = new("问题描述", "Description"),
            ["HC.ColTarget"] = new("目标", "Target"),
            ["HC.SelectIssueHint"] = new("选择上方问题查看详情与修复建议", "Select an issue above to view details and fixes"),
            ["HC.JumpButton"] = new("跳转定位到相关页面", "Go to Related Page"),
            ["HC.CurrentProject"] = new("当前项目：{0}（{1}）", "Current project: {0} ({1})"),
            ["HC.SelectProjectMsg"] = new("请先在项目管理中选择一个项目。", "Please select a project in Project Management first."),
            ["HC.ServiceNotInit"] = new("健康检查服务未初始化。", "The health check service is not initialized."),
            ["HC.Checking"] = new("正在检查，请稍候……", "Checking, please wait…"),
            ["HC.NoIssues"] = new("检查完成，未发现问题。", "Check completed. No issues found."),
            ["HC.CheckFailed"] = new("执行检查失败：{0}", "Check failed: {0}"),
            ["HC.ErrorCount"] = new("错误 {0}", "Errors: {0}"),
            ["HC.WarningCount"] = new("警告 {0}", "Warnings: {0}"),
            ["HC.InfoCount"] = new("提示 {0}", "Info: {0}"),
            ["HC.NotCheckedPassed"] = new("尚未检查或检查通过（{0}）", "Not checked, or no issues found ({0})"),
            ["HC.LastCheck"] = new("最近检查：{0}", "Last check: {0}"),
            ["HC.TargetLabel"] = new("目标：", "Target: "),
            ["HC.DetailLabel"] = new("详情与建议：", "Details & suggestions: "),
            ["HC.JumpTitle"] = new("跳转定位", "Jump to Target"),
            ["HC.JumpSuccess"] = new("已跳转到“{0}”。\n目标：{1} · {2}（名称已复制到剪贴板，便于查找）", "Jumped to \"{0}\".\nTarget: {1} · {2} (name copied to the clipboard for quick search)"),
            ["HC.JumpFailed"] = new("跳转失败：{0}", "Jump failed: {0}"),
            ["HC.TargetCharacter"] = new("角色管理", "Character Management"),
            ["HC.TargetRelationship"] = new("关系网络", "Relationship Network"),
            ["HC.TargetTimeline"] = new("时间线管理", "Timeline Management"),
            ["HC.TargetFaction"] = new("势力管理", "Faction Management"),
            ["HC.TargetPlot"] = new("剧情管理", "Plot Management"),
            ["HC.TargetWorldSetting"] = new("世界设定管理", "World Setting Management"),
            ["HC.TargetVolume"] = new("卷章管理", "Volume & Chapter Management"),
            #endregion

            #region 主题设置（TS.*）
            ["TS.WindowTitle"] = new("主题配置与皮肤设定", "Theme & Skin Settings"),
            ["TS.Title"] = new("主题配置与皮肤设定", "Theme & Skin Settings"),
            ["TS.Subtitle"] = new("内置三种皮肤，支持自定义皮肤与窗口框架颜色；检测到女频文时自动切换红粉花漾少女风", "Three built-in skins, with custom skins and window frame colors; switches to the pink blossom style automatically when a female-oriented novel is detected"),
            ["TS.SkinList"] = new("皮肤列表", "Skin List"),
            ["TS.SelectSkin"] = new("请选择皮肤", "Select a skin"),
            ["TS.ColorPreview"] = new("颜色预览", "Color Preview"),
            ["TS.ApplySkin"] = new("应用皮肤", "Apply Skin"),
            ["TS.AutoByTime"] = new("跟随时间自动切换", "Auto-Switch by Time"),
            ["TS.AutoTimeTooltip"] = new("黑夜 19:00–07:00 自动切换，其余时间白昼", "Auto-switches to night from 19:00 to 07:00; light theme at other times"),
            ["TS.AddCustom"] = new("新增自定义皮肤", "Add Custom Skin"),
            ["TS.AddCustomTooltip"] = new("以当前选中皮肤为基础新增自定义皮肤", "Create a custom skin based on the selected skin"),
            ["TS.EditTooltip"] = new("编辑自定义皮肤的全部颜色（含窗口框架）", "Edit all colors of the custom skin (including window frame)"),
            ["TS.Hint"] = new("提示：内置皮肤不可编辑或删除，可基于它复制为自定义皮肤后修改；切换项目或批量生成检测到女频文时，将临时切换为红粉花漾少女风，退出后自动恢复。", "Tip: built-in skins cannot be edited or deleted; duplicate one as a custom skin to modify it. When switching projects or during batch generation for female-oriented novels, the pink blossom style is applied temporarily and restored afterwards."),
            ["TS.SkinNameHint"] = new("皮肤名称 *", "Skin name *"),
            ["TS.IsDark"] = new("深色基调（使用 MaterialDesign Dark / HandyControl SkinDark 资源）", "Dark base (uses MaterialDesign Dark / HandyControl SkinDark resources)"),
            ["TS.SaveSkin"] = new("保存皮肤", "Save Skin"),
            ["TS.CurrentlyActive"] = new("当前使用中", "In use"),
            // ---- 内置皮肤名称与描述（按语言显示；自定义皮肤保留用户命名） ----
            ["TS.SkinLight"] = new("白昼（浅色）", "Daylight (Light)"),
            ["TS.SkinDark"] = new("黑夜（深色）", "Nightfall (Dark)"),
            ["TS.SkinPink"] = new("红粉花漾少女风", "Pink Blossom"),
            ["TS.KindBuiltin"] = new("内置", "Built-in"),
            ["TS.KindCustom"] = new("自定义", "Custom"),
            ["TS.ToneDark"] = new("深色基调", "Dark tone"),
            ["TS.ToneLight"] = new("浅色基调", "Light tone"),
            // ---- 皮肤颜色项标签（画刷键 → 显示名） ----
            ["TS.C.AppTitleBarBackgroundBrush"] = new("标题栏背景（窗口框架）", "Title bar background (window frame)"),
            ["TS.C.AppTitleBarForegroundBrush"] = new("标题栏文字", "Title bar text"),
            ["TS.C.AppNavPanelBackgroundBrush"] = new("侧边导航背景", "Side navigation background"),
            ["TS.C.AppWindowBackgroundBrush"] = new("窗口背景", "Window background"),
            ["TS.C.AppPanelBackgroundBrush"] = new("面板背景", "Panel background"),
            ["TS.C.AppCardBackgroundBrush"] = new("卡片背景", "Card background"),
            ["TS.C.AppInputBackgroundBrush"] = new("输入框/下拉框背景", "Input & dropdown background"),
            ["TS.C.AppSubtleBorderBrush"] = new("边框颜色", "Border color"),
            ["TS.C.AppMutedTextBrush"] = new("次要文字", "Secondary text"),
            ["TS.C.AppSuccessBrush"] = new("成功/建议文字", "Success & hint text"),
            ["TS.C.AppForegroundTextBrush"] = new("正文文字", "Body text"),
            ["TS.C.PrimaryTextBrush"] = new("主文字（MaterialDesign）", "Primary text (MaterialDesign)"),
            ["TS.C.MaterialDesignBody"] = new("正文文字（MaterialDesign）", "Body text (MaterialDesign)"),
            ["TS.C.MaterialDesignBodyLight"] = new("次要文字（MaterialDesign）", "Secondary text (MaterialDesign)"),
            ["TS.C.MaterialDesignToolForeground"] = new("工具栏文字（MaterialDesign）", "Toolbar text (MaterialDesign)"),
            ["TS.C.MaterialDesignToolTipForeground"] = new("提示文字（MaterialDesign）", "Tooltip text (MaterialDesign)"),
            ["TS.C.MaterialDesignPaper"] = new("对话框纸面（MaterialDesign）", "Dialog surface (MaterialDesign)"),
            ["TS.C.MaterialDesignPrimaryKeyBrush"] = new("主按钮颜色（MaterialDesign）", "Primary button color (MaterialDesign)"),
            ["TS.C.PrimaryBrush"] = new("主色（HandyControl）", "Primary color (HandyControl)"),
            ["TS.C.PrimaryHueMidBrush"] = new("页面头部/强调底色（其上文字为白色）", "Page header & accent background (white text)"),
            ["TS.C.PrimaryHueLightBrush"] = new("徽章/浅强调底色（其上文字为白色）", "Badge & light accent background (white text)"),
            ["TS.C.PrimaryHueDarkBrush"] = new("深强调底色", "Dark accent background"),
            ["TS.C.DataGridRowBackgroundBrush"] = new("表格行背景", "Table row background"),
            ["TS.C.DataGridAltRowBackgroundBrush"] = new("表格交替行背景", "Table alternating row background"),
            ["TS.FemaleModeActive"] = new("女频模式生效中", "Female-oriented mode active"),
            ["TS.CurrentSkinFmt"] = new("当前皮肤：{0}", "Current skin: {0}"),
            ["TS.FemaleSkinName"] = new("红粉花漾少女风（女频自动）", "Pink Blossom (female-oriented, auto)"),
            ["TS.AutoTimeRestored"] = new("已恢复跟随时间自动切换：19:00–07:00 使用黑夜主题，其余时间白昼主题。", "Auto-switch by time restored: night theme from 19:00 to 07:00, light theme at other times."),
            ["TS.CustomSuffix"] = new("{0}·自定义", "{0} (Custom)"),
            ["TS.DeleteCustomConfirm"] = new("确定删除自定义皮肤「{0}」？", "Delete the custom skin \"{0}\"?"),
            ["TS.NameRequired"] = new("请输入皮肤名称", "Please enter a skin name"),
            ["TS.ValidationFailed"] = new("验证失败", "Validation Failed"),
            ["TS.InvalidColor"] = new("「{0}」的颜色值无效：{1}\n请使用 #RRGGBB 或 #AARRGGBB 格式。", "Invalid color value for \"{0}\": {1}\nUse #RRGGBB or #AARRGGBB format."),
            #endregion

            #region 修改启动密码（CPW.*）
            ["CPW.Title"] = new("修改启动密码", "Change Launch Password"),
            ["CPW.EffectNotice"] = new("新密码将于下次启动应用时生效", "The new password takes effect the next time the app starts"),
            ["CPW.CurrentPassword"] = new("当前密码：", "Current password:"),
            ["CPW.NewPassword"] = new("新密码：", "New password:"),
            ["CPW.ConfirmNewPassword"] = new("确认新密码：", "Confirm new password:"),
            ["CPW.Confirm"] = new("确 定", "Confirm"),
            ["CPW.Cancel"] = new("取 消", "Cancel"),
            ["CPW.EnterCurrentPassword"] = new("请输入当前密码", "Please enter the current password"),
            ["CPW.MinLength"] = new("新密码长度不能少于 {0} 位", "The new password must be at least {0} characters"),
            ["CPW.PasswordMismatch"] = new("两次输入的新密码不一致", "The two new passwords do not match"),
            ["CPW.WrongCurrentPassword"] = new("当前密码错误", "The current password is incorrect"),
            ["CPW.ChangeSuccess"] = new("启动密码已更新，下次启动应用时生效。", "Launch password updated. It takes effect the next time the app starts."),
            ["CPW.SuccessTitle"] = new("修改成功", "Changed Successfully"),
            ["CPW.SaveFailed"] = new("保存新密码失败：{0}", "Failed to save the new password: {0}"),
            #endregion

            #region 首次启动引导（FO.*）
            ["FO.WindowTitle"] = new("首次启动向导", "First-Run Wizard"),
            ["FO.OpenConfigDir"] = new("打开配置目录", "Open Configuration Folder"),
            ["FO.CreateTemplate"] = new("创建用户配置模板", "Create User Config Template"),
            ["FO.Finish"] = new("完成并进入系统", "Finish and Enter"),
            ["FO.Intro"] = new("这是首次启动引导。建议在正式使用前先确认以下内容：", "This is the first-run guide. Before getting started, please confirm the following:"),
            ["FO.StatusHint"] = new("请先创建或检查用户配置，然后点击“完成并进入系统”。", "Create or check the user configuration first, then click \"Finish and Enter\"."),
            ["FO.Checklist"] = new(
                "1. 检查数据库与日志目录是否可写。\n" +
                "2. 如需云端 AI，请在用户配置中填写 API Key。\n" +
                "3. 如需本地 AI，请确认 Ollama 或 RWKV 服务已经启动。\n" +
                "4. 用户覆盖配置建议放置在以下路径：\n" +
                "{0}\n\n" +
                "提示：生产环境建议优先使用环境变量覆盖密钥，而不是把密钥直接写入发布目录。",
                "1. Check that the database and log directories are writable.\n" +
                "2. For cloud AI, fill in the API Key in the user configuration.\n" +
                "3. For local AI, make sure the Ollama or RWKV service is running.\n" +
                "4. The user override configuration is recommended to be placed at:\n" +
                "{0}\n\n" +
                "Tip: in production, prefer overriding secrets via environment variables instead of writing them into the publish directory."),
            ["FO.ConfigOpened"] = new("已打开配置目录：{0}", "Configuration folder opened: {0}"),
            ["FO.ConfigOpenFailed"] = new("打开配置目录失败：{0}", "Failed to open the configuration folder: {0}"),
            ["FO.TemplateNotFound"] = new("未找到模板文件：{0}", "Template file not found: {0}"),
            ["FO.TemplateCreated"] = new("已创建用户配置模板：{0}", "User config template created: {0}"),
            ["FO.ConfigExists"] = new("用户配置已存在：{0}", "User configuration already exists: {0}"),
            ["FO.TemplateCreateFailed"] = new("创建用户配置模板失败：{0}", "Failed to create the user config template: {0}"),
            ["FO.SaveStateFailed"] = new("保存首次启动状态失败，请重试。", "Failed to save the first-run state. Please try again."),
            #endregion

            #region AI 配置宿主窗口（AHW.*）
            ["AHW.WindowTitle"] = new("AI模型配置", "AI Model Configuration"),
            ["AHW.ErrorTitle"] = new("AI 模型配置独立测试失败", "AI Model Configuration Standalone Test Failed"),
            ["AHW.ErrorDescription"] = new("页面在独立窗口中初始化时发生异常。请将下面的完整错误详情发回继续排查。", "An exception occurred while initializing the page in the standalone window. Please send back the full error details below to continue troubleshooting."),
            ["AHW.CopyError"] = new("复制错误详情", "Copy Error Details"),
            ["AHW.Copied"] = new("错误详情已复制到剪贴板。", "Error details copied to the clipboard."),
            #endregion

            #region 关联章节选择（CRP.*）
            ["CRP.Title"] = new("关联章节", "Link Chapter"),
            ["CRP.Heading"] = new("关联目标章节", "Link Target Chapter"),
            ["CRP.Description"] = new("依次选择书籍、分卷与章节。关联后，创作助手的后续输入将直接作用于该章节：输入要求即处理（润色/重写/扩写/续写等），也可针对章节提问；输入「取消关联」可解除。", "Select the book, volume and chapter in turn. Once linked, the copilot's subsequent input applies directly to that chapter: enter a request to process it (polish/rewrite/expand/continue, etc.), or ask questions about the chapter; enter \"Unlink\" to remove the link."),
            ["CRP.Book"] = new("书籍", "Book"),
            ["CRP.Volume"] = new("分卷", "Volume"),
            ["CRP.Chapter"] = new("章节", "Chapter"),
            ["CRP.Link"] = new("关联", "Link"),
            ["CRP.LoadBooksFailed"] = new("加载书籍列表失败：{0}", "Failed to load books: {0}"),
            ["CRP.VolumeDisplay"] = new("第{0}卷 {1}", "Vol.{0} {1}"),
            ["CRP.LoadVolumesFailed"] = new("加载分卷失败：{0}", "Failed to load volumes: {0}"),
            ["CRP.ChapterDisplay"] = new("第{0}章 《{1}》", "Ch.{0} \"{1}\""),
            ["CRP.LoadChaptersFailed"] = new("加载章节失败：{0}", "Failed to load chapters: {0}"),
            #endregion

            #region 进度对话框（PD.*）
            ["PD.DefaultTitle"] = new("处理中...", "Processing..."),
            ["PD.DefaultMessage"] = new("请稍候...", "Please wait..."),
            #endregion

            #region 分析结果对话框（AR.*）
            ["AR.WindowTitle"] = new("AI分析结果", "AI Analysis Result"),
            ["AR.SettingNamePlaceholder"] = new("设定名称", "Setting Name"),
            ["AR.ReportSubtitle"] = new("AI智能分析报告", "AI Analysis Report"),
            ["AR.OverallScore"] = new("总体评分", "Overall Score"),
            ["AR.Consistency"] = new("一致性", "Consistency"),
            ["AR.Completeness"] = new("完整性", "Completeness"),
            ["AR.Logical"] = new("逻辑性", "Logic"),
            ["AR.StrengthsHeader"] = new("✅ 优势", "✅ Strengths"),
            ["AR.WeaknessesHeader"] = new("⚠️ 需要改进", "⚠️ Needs Improvement"),
            ["AR.SuggestionsHeader"] = new("💡 改进建议", "💡 Suggestions"),
            ["AR.ConflictsHeader"] = new("🔥 发现的冲突", "🔥 Conflicts Found"),
            ["AR.MissingHeader"] = new("📝 缺失的元素", "📝 Missing Elements"),
            ["AR.AnalysisTimeSample"] = new("分析时间: 2024-12-19 15:30:00", "Analyzed at: 2024-12-19 15:30:00"),
            ["AR.AnalysisTimeFmt"] = new("分析时间: {0}", "Analyzed at: {0}"),
            ["AR.ExportReport"] = new("导出报告", "Export Report"),
            ["AR.ExportDialogTitle"] = new("导出分析报告", "Export Analysis Report"),
            ["AR.FilterMarkdown"] = new("Markdown 文件 (*.md)", "Markdown files (*.md)"),
            ["AR.FilterText"] = new("文本文件 (*.txt)", "Text files (*.txt)"),
            ["AR.ExportSuccessTitle"] = new("导出成功", "Export Succeeded"),
            ["AR.ExportSuccess"] = new("分析报告已导出到：{0}", "Analysis report exported to: {0}"),
            ["AR.ExportFailed"] = new("导出分析报告失败：{0}", "Failed to export the analysis report: {0}"),
            #endregion

            // ---- 批次G2 补充词条（G2 run1 未落盘补齐） ----
            ["HC.JumpSuccess"] = new("已跳转到“{0}”。\n目标：{1} · {2}（名称已复制到剪贴板，便于查找）", "Jumped to \"{0}\".\nTarget: {1} · {2} (name copied to clipboard for easy searching)"),
            ["TS.DeleteCustomConfirm"] = new("确定删除自定义皮肤「{0}」？", "Delete the custom theme \"{0}\"?"),
            ["TS.InvalidColor"] = new("「{0}」的颜色值无效：{1}\n请使用 #RRGGBB 或 #AARRGGBB 格式。", "Invalid color value for \"{0}\": {1}\nUse the #RRGGBB or #AARRGGBB format."),
        };
    }
}
